name: bump
description: |
  Automatically bump the version file of the OG repo

inputs:
  base_branch:
    description: The base branch of the PR.
    required: true
  pr_body:
    description: OG formatted body of the PR description.
    required: true
  pr_title:
    description: SC formatted title of the PR.
    required: true
  pr_number:
    description: PR serial number.
    required: true
  github_repository:
    descripton: Github repository.
    required: true
  dev_branch:
    description: The dev branch of this action to connect to the workflow.
    required: false
    default: 'main'
  changelog_path:
    description: Explicit path to the changelog file.
    require: false
    default: ''


runs:
  using: "composite"
  steps:
    - run: python3 -m pip install semver
      shell: bash
      
    - run: git checkout ${{ github.head_ref }}
      shell: bash
      
    - run: |
        if [ -n "${{ inputs.changelog_path }}" ]; then \
          export CHANGELOG_PATH=${{ inputs.changelog_path }};\
        fi
        export BASE_BRANCH=${{ inputs.base_branch }}
        export PR_NUMBER=${{ inputs.pr_number }}
        export GITHUB_REPOSITORY=${{ inputs.github_repository }}
        cat << \EXPECTMENOTINTHYPRDESCRIPTION | tee /tmp/pr_body
          ${{ inputs.pr_body }}
        EXPECTMENOTINTHYPRDESCRIPTION
        cat << \EXPECTMENOTINTHYPRTITLE | tee /tmp/pr_title
          ${{ inputs.pr_title }}
        EXPECTMENOTINTHYPRTITLE
        python -c "$(wget -qSO- https://raw.githubusercontent.com/XanaduAI/cloud-actions/${{ inputs.dev_branch }}/og/bump/tagger.py 2>/dev/null)" 
      shell: bash
