name: bump
description: |
  Automatically bump the version file of the OG repo

inputs:
  base_branch:
    description: The base branch of the PR.
    required: true
  pr_body:
    description: OG formatted body of the PR description.
    required: true
  pr_title:
    description: SC formatted title of the PR.
    required: true
  dev_branch:
    description: The dev branch of this action to connect to the workflow
    required: false
    default: 'main'

runs:
  using: "composite"

  steps:
    - run: python3 -m pip install semver
      shell: bash
    
    - run: |
        cat << \EOF | export DEFAULT_BRANCH=$(cat -)
          ${{ inputs.base_branch }}
        EOF
        cat << \EOF | export PR_BODY=$(cat -)
          ${{ inputs.pr_body }}
        EOF
        cat << \EOF | export PR_TITLE=$(cat -)
          ${{ inputs.pr_title }}
        EOF
        
        python -c "$(wget -qSO- https://raw.githubusercontent.com/XanaduAI/cloud-actions/${{ inputs.dev_branch }}/og/bump/tagger.py 2>/dev/null)" 
      shell: bash
