name: unit
description: Run unit tests

inputs:
  key:
    description: QUBOT SSH Key
    required: true
  path:
    description: The path for unit tests
    required: false
    default: '.'

runs:
  using: "composite"
  steps:  
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: | 
        eval `ssh-agent`
        echo "${{ inputs.key }}" | ssh-add -
        pip install -r ./requirements.txt
        pip install pytest pytest-cov 
      shell: bash

    - run: |
        COV="$(echo ${{ github.repository }} | cut -d '/' -f2 | sed 's/-/_/g')"
        python -m pytest ${{ inputs.path }} --showlocals --full-trace --cov=${COV} --cov-report xml:coverage.xml --cov-report term-missing --junitxml junit.xml
      shell: bash
