name: unit
description: |
  Run unit tests

inputs:
  key:
    description: QUBOT SSH Key
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        eval `ssh-agent`
        echo "${{ inputs.key }}" | ssh-add -
      shell: bash

    - run: | 
        pip install .
        pip install pytest pytest-cov 
      shell: bash

    - run: |
        python -m pytest --showlocals --full-trace --cov=og_example_plugin --cov-report xml:coverage.xml --cov-report term-missing --junitxml junit.xml
      shell: bash
