name: unit
description: Run unit tests

inputs:
  key:
    description: QUBOT SSH Key
    required: true
  path:
    description: The path for unit tests
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - run: | 
        eval `ssh-agent`
        echo "${{ inputs.key }}" | ssh-add -
        pip install -r ./requirements.txt
        pip install pytest pytest-cov 
      shell: bash

    - run: |
        python -m pytest ${{ inputs.path }} --showlocals --full-trace --cov="$(${GITHUB.repository}|sed 's/-/_/')" --cov-report xml:coverage.xml --cov-report term-missing --junitxml junit.xml
      shell: bash
