name: unit
description: Run unit tests

inputs:
  key:
    description: QUBOT SSH Key
    required: true
  repository:
    description: name of the repository
    required: true
  path:
    description: The path for unit tests
    required: false
    default: '.'
  pip_command:
    descrption: Custom pip install command
    required: false
    default: 'pip install -r ./requirements.txt'

runs:
  using: "composite"
  steps:
    - run: | 
        eval `ssh-agent`
        echo "${{ inputs.key }}" | ssh-add -
        `${{ inputs.pip_command }}`
        pip install pytest pytest-cov 
      shell: bash

    - run: |
        COV="$(echo ${{ inputs.repository }} | cut -d '/' -f2 | sed 's/-/_/g')"
        python -m pytest ${{ inputs.path }} --showlocals --full-trace --cov=${COV} --cov-report xml:coverage.xml --cov-report term-missing --junitxml junit.xml
      shell: bash
