name: Label External Pull Requests
description: Checks if a PR is a fork and applies an external label accordingly

inputs:
  github_token:
    description: The GitHub token to use read member status
    required: true
  github_team:
    description: The team slug for external collaborators
    required: true
  github_organization:
    description: The organization to check membership
    required: true
  github_username:
    description: The username to check membership 
    required: true

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      id: set-result
      env:
         GITHUB_ORGANIZATION: ${{ inputs.github_organization }}
         GITHUB_TEAM_SLUG: ${{ inputs.github_team }}
         GITHUB_USERNAME: ${{ inputs.github_username }}
      with: 
        github-token: ${{ inputs.github_token }}
        result-encoding: string
        script: |
          if ((await github.rest.orgs.getMembershipForUser({
              org: process.env.GITHUB_ORGANIZATION,
              username: process.env.GITHUB_USERNAME,
              })).data.state === 'active') {
                if ((await github.rest.teams.getMembershipForUserInOrg({
                  org: process.env.GITHUB_ORGANIZATION,
                  team_slug: process.env.GITHUB_TEAM_SLUG,
                  username: process.env.GITHUB_USERNAME,
                  })).data.state === 'active') {
                  return true;
                }
            return false;
          } 
    - name: Add label
      shell: bash
      env:
        PR_HTML_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ github.token }}
      if: github.event.pull_request.head.repo.fork == true || steps.set-result.outputs.result == 'true'
      run: gh pr edit "$PR_HTML_URL" --add-label "external"
            
