name: Label External Pull Requests
description: Checks if a PR is a fork and applies an external label accordingly


runs:
  using: composite
  steps:
    - name: Check if fork and label
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
            if [ '${{ github.event.pull_request.head.repo.fork}}'=='false' ]; then 
                gh pr edit ${{github.event.pull_request.html_url}} --add-label "external"; 
            fi 
    
    - uses: actions/github-script@v7
      id: set-result
      with: #/orgs/PennyLaneAI/teams/external-collaborators/members
        script: |
          return github.rest.issues.organizations.members({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
              })
        result-encoding: json
    - name: Get result
      shell: bash
      run: echo "${{ github.actor }} ${{steps.set-result.outputs.result}}"
