name: Label External Pull Requests
description: Checks if a PR is a fork and applies an external label accordingly


runs:
  using: composite
  steps:
    - name: Check if fork and label
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
            if [ '${{ github.event.pull_request.head.repo.fork}}'=='false' ]; then 
                gh pr edit ${{github.event.pull_request.html_url}} --add-label "external"; 
            fi
    
    - uses: actions/github-script@v7
      id: set-result
      with: #/orgs/PennyLaneAI/teams/external-collaborators/members
        script: |
          return github.rest.teams.listMembershipsForOrg({
            org: context.repo.owner,
            team_slug: "external-collaborators",
            username: ${{ github.actor }}
              })
    - name: Get result
      shell: bash
      run: gh api /orgs/${{context.repo.owner}}/teams/external-collaborators/memberships/${{ github.actor }}
