name: Label External Pull Requests
description: Checks if a PR is a fork and applies an external label accordingly

inputs:
  git_read_member:
    description: The GitHub token to use read member status
    required: true
  team:
    description: The team slug for external collaborators
    required: true
  org:
    description: The organization to check membership in
    required: true

runs:
  using: composite
  steps:
    - name: Check if fork and label
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
            if [ '${{ github.event.pull_request.head.repo.fork}}'=='false' ]; then 
                gh pr edit ${{github.event.pull_request.html_url}} --add-label "external"; 
            fi
    
    - uses: actions/github-script@v7
      id: set-result
      with: 
        github-token: ${{ github.token }}
        script: |
            const result = github.rest.teams.getMembershipForUserInOrg({
              org: "${{ inputs.org }}",
              team_slug: "${{ inputs.team }}",
              username: "${{ inputs.git_read_member }}",
                });
            return result.data.state;
            
    - name: Get result
      shell: bash
      run: echo "result is ${{ steps.set-result.outputs.result }}"
            
