name: Restrict merging to the specified destination branch only from a specified source branch
description: A pull request can be merged only if the both the source and destination branches conform to the specified branch names.

inputs:
  source-branch:
    description: The name of the source branch
    required: true
  destination-branch:
    description: The name of the destination branch
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]
        then
          if [[ "$GITHUB_HEAD_REF" == "${{ inputs.source-branch }}" ]]
          then
            echo "Source Branch, $GITHUB_HEAD_REF is ok"
            if [[ "$GITHUB_BASE_REF" == "${{ inputs.destination-branch }}" ]]
            then
              echo "Destination branch, $GITHUB_BASE_REF is ok"
              exit 0
            else
              echo "Destination branch should be ${{ inputs.destination-branch }} and not $GITHUB_BASE_REF"
              exit 1
            fi
          else
            echo "Source branch should be ${{ inputs.source-branch }} and not $GITHUB_HEAD_REF"
            exit 1
          fi
        fi
