name: Build Docker Image
description: Builds a Docker image (with BuildKit enabled).

inputs:
  path:
    description: Docker build context path (e.g., ".").
    required: true
  target:
    description: Docker build target (e.g., "server").
    required: true
  tag:
    description: Docker build image tag (e.g., "server-production").
    required: true
  docker-build-extra-args:
    description: Docker build extra arguments (e.g., "--build-arg DEBUG=false").
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      env:
        DOCKER_BUILDKIT: 1
      run:
        docker build \
          --ssh default \
          --tag ${{ inputs.tag }} \
          --target ${{ inputs.target }} \
          --build-arg COMMIT_SHA=${{ github.sha }} \
          ${{ inputs.docker-build-extra-args }} \
          ${{ inputs.path }}
