name: lint
description: |
  Run formatters/linters to OG specifications

runs:
  using: "composite"
  steps:
    - run: | 
          pip install black isort docformatter flake8
      shell: bash

    - run: |
          MODIFIED_PY_FILES="$(git diff --diff-filter=MAC --name-only | grep -i '\.py$')"
          if [ -n "${MODIFIED_PY_FILES}"]; then \
            black "${MODIFIED_PY_FILES}" ; \
            isort --profile=black "${MODIFIED_PY_FILES}" ; \
            docformatter --recursive --in-place --wrap-summaries 88 --wrap-descriptions 88 "${MODIFIED_PY_FILES}" ; \
            flake8 --ignore=E203,E501,W503 "${MODIFIED_PY_FILES}" ; \
          fi
      shell: bash
