name: Generate Docker Image Tags
description: Generate a list of Docker image tags for the current workflow.
# The returned tags depend on the branch the workflow runs on:
#    * If the current branch is a development branch (i.e. not master or main),
#      the image will receive "development" tags (prefixed with "dev."). It will
#      be tagged with both the commit hash and the branch name. For example, a
#      commit on branch "feature-branch" with hash "425840e" will receive the
#      following tags: {dev.feature-branch, dev.425840e}.
#
#    * If the current branch is master or main, the image will receive the same
#      tags (branch and commit hash) but without the "dev." prefix. It will also
#      receive the special "latest" tag that Docker uses by default. For example,
#      a commit on branch "master" with hash "425840e" will receive the following
#      tags: {latest, master, 425840e}

inputs:
  shortcut-api-token:
    description: Shortcut API token for fetching Story IDs related to a PR.
    required: false
  prefix:
    description: |
      The prefix for tagging commits that are not yet merged to main/master.
      For example: a PR from some-branch would receive the tags <prefix>.some-branch, <prefix>.<COMMIT_SHA>.
    required: false
    default: dev

outputs:
  tags:
    description: Comma-separated list of tags.
    value: ${{ steps.get-tags.outputs.tags }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: pip

    - name: Execute generate-docker-image-tags.py
      run: python .github/actions/generate-docker-image-tags/generate-docker-image-tags.py
      shell: bash
  