name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Tags
        id: tags
        uses: ./generate-docker-image-tags
        with:
          shortcut-api-token: Mock

      - name: Display Tags
        run: |
          echo ${{ steps.tags.outputs.tags }}
