name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Tags
        id: tags
        uses: ./generate-docker-image-tags

      - name: Display Tags
        run: |
          echo ${{ steps.tags.outputs.tags }}
